### ISSUE TITLE
上传报错

### ISSUE THREAD

**Issue by inkss** [pluveto/upgit#41]
错误日志：

```log
2022-04-22 00:38:06.977034861 +0800 CST m=+0.000697220[INFO ] Started
2022-04-22 00:38:06.977117796 +0800 CST m=+0.000780054[ERROR] abort: $HOME is not defined
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.18.0-beta1/x64/src/runtime/debug/stack.go:24 +0x65
github.com/pluveto/upgit/lib/xlog.Verbose.Log({0x38?, 0x61?, {0xc0000160f0?, 0xc000091c80?}, 0x40ce47?}, {0x71bc87, 0x8}, {0xc000091ca0?, 0xc000091cc8?}, {0x0, ...})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:55 +0x12a
github.com/pluveto/upgit/lib/xlog.Verbose.Error(...)
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:44
github.com/pluveto/upgit/lib/xlog.AbortErr({0x7a6000?, 0xc000020f80?})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:93 +0xf9
main.loadConfig(0x957160)
	/Users/runner/work/upgit/upgit/main.go:191 +0x8f
main.mainCommand()
	/Users/runner/work/upgit/upgit/main.go:49 +0x35
main.main()
	/Users/runner/work/upgit/upgit/main.go:40 +0x7b
```

**Comment by pluveto** [comment]
Fixed. See next prerelease

**Comment by inkss** [comment]
能发一个beta版本吗

**Comment by pluveto** [comment]
https://github.com/pluveto/upgit/releases/tag/v0.2.16

**Comment by inkss** [comment]
```log
2022-04-22 01:16:29.048806412 +0800 CST m=+0.000678423[INFO ] Started
2022-04-22 01:16:29.048987304 +0800 CST m=+0.000859219[INFO ] uploader: lskypro2
2022-04-22 01:16:29.049032612 +0800 CST m=+0.000904541[ERROR] abort: unknown uploader: lskypro2
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.18.0-beta1/x64/src/runtime/debug/stack.go:24 +0x65
github.com/pluveto/upgit/lib/xlog.Verbose.Log({0x20?, 0xe2?, {0xc0000160f0?, 0xc00001e232?}, 0x7fe9921a54d0?}, {0x71bc87, 0x8}, {0xc00001a600?, 0x957b20?}, {0x0, ...})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:55 +0x12a
github.com/pluveto/upgit/lib/xlog.Verbose.Error(...)
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:44
github.com/pluveto/upgit/lib/xlog.AbortErr({0x7a6000?, 0xc0000210a0?})
	/Users/runner/work/upgit/upgit/lib/xlog/verbose.go:93 +0xf9
main.dispatchUploader()
	/Users/runner/work/upgit/upgit/main.go:358 +0xb34
main.mainCommand()
	/Users/runner/work/upgit/upgit/main.go:60 +0x8f
main.main()
	/Users/runner/work/upgit/upgit/main.go:40 +0x7b
```



config:
```toml
default_uploader = "lskypro2"

rename = "{year}/{month}/upgit_{year}{month}{day}_{unix_ts}{ext}"

[output_formats]
"bbcode" = "[img]{url}[/img]"
"html" = '<img src="{url}" />'
"markdown-simple" = "![]({url})"

[uploaders.lskypro2]
host = "https://test.7bu.top"
token = "3***Di9xIL"

```
